# Generated by Django 4.2.4 on 2023-08-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='development_type',
            field=models.CharField(choices=[('Front', 'Frontend'), ('Back', 'Backend')], default='Front', max_length=5),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='level',
            field=models.CharField(choices=[('Low', 'Basic'), ('Mid', 'Intermediate'), ('High', 'Advanced')], max_length=4),
        ),
    ]
