# Generated by Django 4.2.4 on 2023-08-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_instrument_development_type_alter_instrument_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='level',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=12),
        ),
    ]
