# Generated by Django 4.2.4 on 2023-08-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_instrument_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telegram_profile_linl',
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='telegram username'),
        ),
    ]
