# Generated by Django 4.2.4 on 2023-08-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_user_telegram_profile_linl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='development_type',
            field=models.CharField(choices=[('Front', 'Frontend'), ('Back', 'Backend')], max_length=5),
        ),
    ]
